name: CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-lates

    steps:

      - uses: actions/checkout@v3

      - name: Hola mundo
        run: |
          echo "hola mundo"
          
      - name: Hola mundo 2
        run: |
          echo "hola mundo 2"

  
